spring:
  application:
    name: translation-service
  profiles:
    active: dev

jwt:
  secret: 5adbcb3f03ff0c8b610e62f6db989111e781880719061e4aed7e3d57fbe9272f2dbf05bc
  expiration: 86400000

logging:
  level:
    root: INFO
    com.digitaltolk.translation_service: DEBUG  # Enable debug logs for your package
    org.hibernate.SQL: DEBUG                   # Show SQL statements
    org.hibernate.type: TRACE                  # Show parameter binding

---
# DEV PROFILE
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: digitaltolk
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false  # Disable since we're using logging for SQL
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  testdata:
    enabled: true
    record-count: 100000
    batch-size: 1000
    tags: ['mobile', 'desktop', 'web']
    locales: ['en', 'fr', 'es']

# Add logging level for dev profile
logging:
  level:
    com.digitaltolk.translation_service.factory: DEBUG

---
# PRODUCTION PROFILE
spring:
  config:
    activate:
      on-profile: prod
  # ... prod config ...